---
# Ansible Module apt https://docs.ansible.com/ansible/2.9/modules/apt_module.html#apt-module
- name: Run the equivalent of "apt-get update" as a separate step
  tags: linux,debian,ubuntu,apt,update
  ansible.builtin.apt:
    update_cache: true
- name: Install multiple APT packages sequentially
  tags: linux,debian,ubuntu,apt,install
  ansible.builtin.apt:
    name: '{{ item }}'
    state: present
  loop:
    - apache2
    - grep
    - nmap
    - python3
    - tree
- name: Remove useless packages from the cache
  tags: linux,debian,ubuntu,apt,cache,clean
  ansible.builtin.apt:
    autoclean: true
- name: Remove dependencies that are no longer required
  tags: linux,debian,ubuntu,apt,cache,remove
  ansible.builtin.apt:
    autoremove: true
- name: Include - Node Exporter
  tags: linux,debian,ubuntu,include,nodeexporter,setup
  ansible.builtin.include_tasks: install-nodeexporter.yml
- name: Include - Java JDK8
  tags: linux,redhat,centos,include,jdk8,setup
  ansible.builtin.include_tasks: install-jdk8.yml
