global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
    - targets: ["localhost:9090"]
  - job_name: "node-exporter-ubuntu-arm"
    static_configs:
    - targets: ["10.0.0.11:9100"]
  - job_name: "node-exporter-centos-arm"
    static_configs:
    - targets: ["10.0.0.125:9100"]
  - job_name: "wmi-exporter-win11-arm"
    static_configs:
    - targets: ["10.0.0.220:9182"]