services:
  ubuntu:
    command: tail -f /dev/null
    container_name: docker-ubuntu
    restart: unless-stopped
    working_dir: /var/lib/ubuntu
    build:
      context: .
      dockerfile: ./ubuntu/Dockerfile
    networks:
      - customnet
    ports:
      - 58898:22
    volumes:
      - type: bind
        source: ./ubuntu/mount
        target: /var/lib/ubuntu/mount
        read_only: false
networks:
  customnet: